# AdaptiveMusicTrack — runtime controller for an adaptive music track.
#
# Generated by pipelines/audio/adaptive_music.py. Do not hand-edit; re-run
# the Python tool to regenerate.
#
# How it works:
#  - One AudioStreamSynchronized resource holds N synchronized stems.
#  - Each stem has its own bus (Music_<stem_id>) so volume can be mixed live.
#  - set_intensity(level) maps 0..1 to per-stem volume_db using each stem's
#    intensity_min/intensity_max envelope.
#  - set_state(name) looks up the state in `STATES` and applies its intensity.
#  - crossfade_to() tweens volume_db down then loads + starts the next track.

extends Node
class_name AdaptiveMusicTrack_combat_a

const STEMS: Array = [{"id": "drums", "intensity_min": 0.0, "intensity_max": 1.0}, {"id": "bass", "intensity_min": 0.0, "intensity_max": 1.0}, {"id": "lead", "intensity_min": 0.4, "intensity_max": 1.0}, {"id": "perc_hi", "intensity_min": 0.7, "intensity_max": 1.0}]
const STATES: Dictionary = {"calm": {"intensity": 0.2}, "tense": {"intensity": 0.6}, "combat": {"intensity": 0.9}, "victory": {"intensity": 1.0, "next_track": "victory_a"}}
const BPM: float = 120
const BARS: int = 16
const LOOP: bool = true

var _intensity: float = 1.0
var _stream_sync: AudioStreamSynchronized
var _player: AudioStreamPlayer

func _ready() -> void:
	_player = AudioStreamPlayer.new()
	_player.bus = "Music"
	add_child(_player)
	_player.stream = _build_synchronized_stream()
	apply_intensity(_intensity)

func _build_synchronized_stream() -> AudioStreamSynchronized:
	var sync := AudioStreamSynchronized.new()
	sync.stream_count = STEMS.size()
	for i in range(STEMS.size()):
		var info: Dictionary = STEMS[i]
		var stem_path := "res://audio/music/combat_a/{stem}.wav".format({{"stem": info.id}})
		var stream: AudioStream = load(stem_path)
		sync.set_sync_stream(i, stream)
		sync.set_sync_stream_volume(i, 0.0)
	return sync

func play() -> void:
	if _player and not _player.playing:
		_player.play()

func stop() -> void:
	if _player and _player.playing:
		_player.stop()

func set_intensity(level: float) -> void:
	_intensity = clamp(level, 0.0, 1.0)
	apply_intensity(_intensity)

func apply_intensity(level: float) -> void:
	for i in range(STEMS.size()):
		var info: Dictionary = STEMS[i]
		var lo: float = info.get("intensity_min", 0.0)
		var hi: float = info.get("intensity_max", 1.0)
		var v: float = 0.0
		if level <= lo:
			v = -80.0
		elif level >= hi:
			v = 0.0
		else:
			# Linear ramp -80 dB -> 0 dB across [lo, hi]
			v = lerp(-80.0, 0.0, (level - lo) / max(hi - lo, 0.001))
		_stream_sync = _player.stream as AudioStreamSynchronized
		if _stream_sync:
			_stream_sync.set_sync_stream_volume(i, v)

func set_state(name: String) -> void:
	if not STATES.has(name):
		push_warning("[AdaptiveMusicTrack] unknown state: %s" % name)
		return
	var st: Dictionary = STATES[name]
	if st.has("intensity"):
		set_intensity(float(st["intensity"]))
	if st.has("next_track"):
		# Caller is expected to load the next track and crossfade.
		emit_signal("state_requests_track_change", st["next_track"])

signal state_requests_track_change(track_id: String)

func crossfade_to(other: AdaptiveMusicTrack, seconds: float = 4.0) -> void:
	if other == null:
		return
	var tween := create_tween().set_parallel(true)
	tween.tween_property(_player, "volume_db", -80.0, seconds)
	other.play()
	tween.tween_property(other._player, "volume_db", 0.0, seconds).from(-80.0)
	tween.finished.connect(stop)
