# AUTO-GENERATED by pipelines/game_data/export_godot.py
# Source of truth: D:/assets/pipelines/game_data/schemas.py
# Regenerate with: python pipelines/game_data/export_godot.py

class_name AbilityRecord
extends Resource

@export var id: String = ""
@export var display_name: String = ""
@export var schema_version: String = "1.0.0"
@export var tags: Array = []
@export var localization_key: String = ""
@export var provenance: Dictionary = {}  # nested Provenance
@export var notes: String = ""
@export var kind: String = ""  # enum: active, passive, channel, toggle
@export var school: String = ""  # enum: physical, elemental, arcane, nature, shadow, holy
@export var tier: int = 1
@export var shape: String = ""  # enum: projectile, self, aura, cone, line, point, touch
@export var cost: Dictionary = {}  # nested AbilityCost
@export var effect: Dictionary = {}  # nested AbilityEffect
@export var icon_id: String = ""  # nullable
@export var vfx_id: String = ""  # nullable
@export var sfx_id: String = ""  # nullable
@export var description: String = ""
