# AUTO-GENERATED by pipelines/game_data/export_godot.py
# Source of truth: D:/assets/pipelines/game_data/schemas.py
# Regenerate with: python pipelines/game_data/export_godot.py

class_name FactionRecord
extends Resource

@export var id: String = ""
@export var display_name: String = ""
@export var schema_version: String = "1.0.0"
@export var tags: Array = []
@export var localization_key: String = ""
@export var provenance: Dictionary = {}  # nested Provenance
@export var notes: String = ""
@export var ideology: String = ""
@export var primary_color: String = ""
@export var secondary_color: String = ""
@export var territory: Array = []
@export var allies: Array = []
@export var enemies: Array = []
@export var sigil_prompt: String = ""
@export var description: String = ""
