# AUTO-GENERATED by pipelines/game_data/export_godot.py
# Source of truth: D:/assets/pipelines/game_data/schemas.py
# Regenerate with: python pipelines/game_data/export_godot.py

class_name ItemRecord
extends Resource

@export var id: String = ""
@export var display_name: String = ""
@export var schema_version: String = "1.0.0"
@export var tags: Array = []
@export var localization_key: String = ""
@export var provenance: Dictionary = {}  # nested Provenance
@export var notes: String = ""
@export var category: String = ""  # enum: weapon, armor, consumable, material, quest, tool
@export var rarity: String = "common"  # enum: common, uncommon, rare, epic, legendary
@export var damage_type: String = ""  # enum: physical, fire, cold, lightning, poison, arcane, holy, shadow; nullable
@export var stats: Dictionary = {}  # nested ItemStats
@export var icon_id: String = ""  # nullable
@export var description: String = ""
@export var stack_max: int = 1
