# AUTO-GENERATED by pipelines/game_data/export_godot.py
# Source of truth: D:/assets/pipelines/game_data/schemas.py
# Regenerate with: python pipelines/game_data/export_godot.py

class_name LoreTermRecord
extends Resource

@export var id: String = ""
@export var display_name: String = ""
@export var schema_version: String = "1.0.0"
@export var tags: Array = []
@export var localization_key: String = ""
@export var provenance: Dictionary = {}  # nested Provenance
@export var notes: String = ""
@export var canonical_spelling: String = ""
@export var aliases: Array = []
@export var category: String = ""  # enum: place, person, concept, artifact, event, deity
@export var description: String = ""
@export var source_doc: String = ""  # nullable
