# AUTO-GENERATED by pipelines/game_data/export_godot.py
# Source of truth: D:/assets/pipelines/game_data/schemas.py
# Regenerate with: python pipelines/game_data/export_godot.py

class_name NpcRecord
extends Resource

@export var id: String = ""
@export var display_name: String = ""
@export var schema_version: String = "1.0.0"
@export var tags: Array = []
@export var localization_key: String = ""
@export var provenance: Dictionary = {}  # nested Provenance
@export var notes: String = ""
@export var role: String = ""  # enum: vendor, questgiver, enemy, ally, neutral, boss
@export var faction_id: String = ""  # nullable
@export var biome: String = ""  # nullable
@export var level: int = 1
@export var health: int = 100
@export var abilities: Array = []
@export var dialogue_start: String = ""  # nullable
@export var description: String = ""
