"""Codegen Godot 4.5 Resource scripts + .tres files from validated records.

For each record_type in schemas.RECORD_TYPES we emit:

  godot/scripts/<type>_record.gd   - GDScript Resource class with @export fields
  godot/resources/<type>s/<id>.tres - one .tres per validated record

The class_name in the .gd file corresponds to PascalCase of the record type.
.tres files reference the script via ext_resource. Drop the entire godot/
folder into a Godot 4.5 project at res://game_data/ and the resources will
import as first-class typed Resources.

Per F_game_data: JSONL is for manufacturing, .tres is for shipping.

We pick GDScript over C# Resource codegen because:
  - Godot 4.5 docs treat both equally for [GlobalClass] resources
  - this project's existing godot_pack/* shaders are GDScript-style
  - .gd codegen is simpler and the runtime behavior is identical
A C# variant can be added later if the project standardizes on Mono.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

import sys
ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from schemas import RECORD_TYPES, plural  # noqa: E402

GAME_DATA = Path(r"D:\assets\game_data")
VALIDATED = GAME_DATA / "validated"
GODOT_OUT = GAME_DATA / "godot"


# Pydantic JSON-Schema -> GDScript type mapping.
# We hand-code this because Godot's @export type set is small and the schemas
# are deterministic.
PRIMITIVE = {
    ("integer", None): "int",
    ("number", None): "float",
    ("string", None): "String",
    ("boolean", None): "bool",
}


def to_pascal(snake: str) -> str:
    return "".join(p.capitalize() for p in snake.split("_"))


def gd_default(field_schema: dict[str, Any], gd_type: str) -> str:
    """Return GDScript-syntax default for an @export var."""
    if "default" in field_schema:
        d = field_schema["default"]
        if d is None:
            return ""  # leave un-defaulted; Godot emits `null` for nullable
        if gd_type == "String":
            return f'"{d}"'
        if gd_type == "Array":
            return "[]"
        if gd_type == "bool":
            return "true" if d else "false"
        return repr(d)
    if gd_type == "String":
        return '""'
    if gd_type == "Array":
        return "[]"
    if gd_type == "int":
        return "0"
    if gd_type == "float":
        return "0.0"
    if gd_type == "bool":
        return "false"
    return ""


def field_type_for(prop: dict[str, Any], defs: dict[str, Any]) -> tuple[str, str]:
    """(gd_type, hint_comment). Returns 'String' for enums (Literal), 'Array'
    for lists, plain int/float/String/bool otherwise. Nested objects are
    expressed as Dictionary with a comment. We never recurse into a class for
    nested structs: Godot Resources can certainly do this, but the JSONL data
    flat-maps cleanly to Dictionary which we then unpack at game runtime.
    """
    # $ref - resolve
    if "$ref" in prop:
        ref = prop["$ref"].split("/")[-1]
        if ref in defs:
            return ("Dictionary", f"nested {ref}")
        return ("Dictionary", "")
    # anyOf - usually `Type | None` (nullable)
    if "anyOf" in prop:
        non_null = [s for s in prop["anyOf"] if s.get("type") != "null"]
        if non_null:
            gd, hint = field_type_for(non_null[0], defs)
            extra = "nullable"
            combined = f"{hint}; {extra}" if hint else extra
            return (gd, combined)
        return ("Variant", "")
    t = prop.get("type")
    if t == "array":
        return ("Array", "")
    if t == "object":
        return ("Dictionary", "")
    if t in ("integer",):
        return ("int", "")
    if t in ("number",):
        return ("float", "")
    if t == "boolean":
        return ("bool", "")
    if t == "string":
        if "enum" in prop:
            return ("String", "enum: " + ", ".join(prop["enum"]))
        return ("String", "")
    return ("Variant", "")


def make_gd_class(record_type: str) -> str:
    cls = RECORD_TYPES[record_type]
    schema = cls.model_json_schema()
    defs = schema.get("$defs", {})
    pascal = to_pascal(record_type) + "Record"
    lines = [
        "# AUTO-GENERATED by pipelines/game_data/export_godot.py",
        "# Source of truth: D:/assets/pipelines/game_data/schemas.py",
        "# Regenerate with: python pipelines/game_data/export_godot.py",
        "",
        f"class_name {pascal}",
        "extends Resource",
        "",
    ]
    props = schema.get("properties", {})
    for fname, fspec in props.items():
        gd_type, hint = field_type_for(fspec, defs)
        default = gd_default(fspec, gd_type)
        # Godot @export needs an initial value for nullable fields too;
        # default to the type's zero value if none provided so .tres can
        # always assign without a setter complaint.
        if not default:
            zero = {"int": "0", "float": "0.0", "bool": "false",
                    "String": '""', "Array": "[]", "Dictionary": "{}"}.get(gd_type)
            if zero is not None:
                default = zero
        decl = f"@export var {fname}: {gd_type}"
        if default:
            decl += f" = {default}"
        if hint:
            decl += f"  # {hint}"
        lines.append(decl)
    lines.append("")
    return "\n".join(lines)


def gd_value_lit(v: Any) -> str:
    """Emit a GDScript literal for use in .tres."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        # escape backslash and double-quote
        s = v.replace("\\", "\\\\").replace('"', '\\"')
        # collapse newlines
        s = s.replace("\n", "\\n")
        return f'"{s}"'
    if isinstance(v, list):
        return "[" + ", ".join(gd_value_lit(x) for x in v) + "]"
    if isinstance(v, dict):
        # GDScript dict literal: { "k": v, ... }
        parts = []
        for k, val in v.items():
            parts.append(f'"{k}": {gd_value_lit(val)}')
        return "{ " + ", ".join(parts) + " }"
    return "null"


def make_tres(record_type: str, record: dict[str, Any]) -> str:
    pascal = to_pascal(record_type) + "Record"
    script_path = f"res://game_data/scripts/{record_type}_record.gd"
    lines = [
        # Godot 4.x .tres header. load_steps must include external script.
        '[gd_resource type="Resource" script_class="' + pascal + '" load_steps=2 format=3]',
        "",
        f'[ext_resource type="Script" path="{script_path}" id="1"]',
        "",
        "[resource]",
        f'script = ExtResource("1")',
    ]
    for k, v in record.items():
        lines.append(f"{k} = {gd_value_lit(v)}")
    return "\n".join(lines) + "\n"


def safe_filename(s: str) -> str:
    # collapse anything weird; the validated id is already snake_case but be safe
    return re.sub(r"[^a-z0-9_-]", "_", s.lower())


def export_all(validated_dir: Path = VALIDATED, godot_dir: Path = GODOT_OUT) -> dict[str, int]:
    scripts_dir = godot_dir / "scripts"
    res_root = godot_dir / "resources"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    res_root.mkdir(parents=True, exist_ok=True)

    counts: dict[str, int] = {}
    for record_type in RECORD_TYPES:
        # 1. emit GDScript class
        gd_text = make_gd_class(record_type)
        (scripts_dir / f"{record_type}_record.gd").write_text(gd_text, encoding="utf-8")

        # 2. emit one .tres per validated record
        in_path = validated_dir / f"{plural(record_type)}.jsonl"
        records = []
        if in_path.exists():
            for line in in_path.read_text(encoding="utf-8").splitlines():
                if line.strip():
                    records.append(json.loads(line))

        type_dir = res_root / plural(record_type)
        type_dir.mkdir(parents=True, exist_ok=True)
        desired = {safe_filename(rec["id"]) + ".tres" for rec in records}
        for stale in type_dir.glob("*.tres"):
            if stale.name not in desired:
                stale.unlink()
        for rec in records:
            rid = safe_filename(rec["id"])
            tres_text = make_tres(record_type, rec)
            (type_dir / f"{rid}.tres").write_text(tres_text, encoding="utf-8")
        counts[record_type] = len(records)

    # 3. write a project_readme.txt explaining the drop-in workflow
    readme = (
        "# game_data drop-in for Godot 4.5\n"
        "Copy this folder to res://game_data/. The scripts/ subfolder contains\n"
        "auto-generated Resource classes; resources/<type>s/*.tres are the data\n"
        "records. Reference any record from GDScript:\n\n"
        '    var rec: ItemRecord = load("res://game_data/resources/items/iron_sword_0.tres")\n'
        "    print(rec.display_name, rec.stats)\n\n"
        "All fields use @export so they show in the Inspector.\n"
        "Regenerate from D:/assets/ with:\n"
        "    python pipelines/game_data/export_godot.py\n"
    )
    (godot_dir / "README.txt").write_text(readme, encoding="utf-8")
    return counts


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--validated", type=Path, default=VALIDATED)
    ap.add_argument("--out", type=Path, default=GODOT_OUT)
    args = ap.parse_args()
    counts = export_all(validated_dir=args.validated, godot_dir=args.out)
    total = sum(counts.values())
    print(f"[export_godot] wrote {total} .tres files")
    for rt, n in counts.items():
        print(f"  {rt:11s}: {n}")
    print(f"  -> {args.out}")


if __name__ == "__main__":
    main()
